# Generated by Django 4.1 on 2022-09-06 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_poost_delete_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poost",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 9, 6, 10, 2, 2, 655795, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
